<a href="https://colab.research.google.com/github/ranabhumi2022/Classification-ML-projects/blob/main/classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Q12 classification
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
from google.colab import files
uploaded= files.upload()
import os
print(os.listdir())
#load dataset
df=pd.read_csv("heart.csv")
print(df.info())

#  feature marking seperate  feature  X and Y
X=df.drop("HeartDisease",axis=1)
Y=df['HeartDisease']
print(df.head())
X = pd.get_dummies(X, drop_first=True)
scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

# Train the model split dataset into training (70%)
X_train, X_test, Y_train, Y_test=train_test_split(X_scaled,Y,test_size=0.2,random_state=42)
model=LogisticRegression(max_iter=2000)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)
# coefficient and intercept
print("intercept:",model.intercept_)
print("coefficent:",model.coef_)
accuracy=accuracy_score(Y_test,Y_pred)
print("accuracy:",accuracy)
cm=confusion_matrix(Y_test,Y_pred)
print("confusion matrix :\n",cm)

# New sample input (same format as dataset)
new_data = {
    'General_Health': 'Very Good',
    'Checkup': 'Within 1 year',
    'Exercise': 'Yes',
    'Skin_Cancer': 'No',
    'Other_Cancer': 'No',
    'Depression': 'No',
    'Diabetes': 'No',
    'Arthritis': 'No',
    'Sex': 'Male',
    'Age_Category': '30-34',
    'Height_(cm)': 170,
    'Weight_(kg)': 70,
    'BMI': 24.2,
    'Smoking_History': 'No',
    'Alcohol_Consumption': 2,
    'Fruit_Consumption': 3,
    'Green_Vegetables_Consumption': 4,
    'FriedPotato_Consumption': 1
}

import pandas as pd

new_df = pd.DataFrame([new_data])

# Same preprocessing
new_df = pd.get_dummies(new_df)

# Match training columns
new_df = new_df.reindex(columns=X.columns, fill_value=0)

# Scale
new_df_scaled = scaler.transform(new_df)

# Predict
prediction = model.predict(new_df_scaled)

print("Prediction (0 = No, 1 = Yes):", prediction)



Saving heart.csv to heart (4).csv
['.config', 'heart.csv', 'heart (1).csv', 'loan_data.csv', 'heart (2).csv', 'heart (4).csv', 'heart (3).csv', '.ipynb_checkpoints', 'sample_data']
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   Age             918 non-null    int64  
 1   Sex             918 non-null    object 
 2   ChestPainType   918 non-null    object 
 3   RestingBP       918 non-null    int64  
 4   Cholesterol     918 non-null    int64  
 5   FastingBS       918 non-null    int64  
 6   RestingECG      918 non-null    object 
 7   MaxHR           918 non-null    int64  
 8   ExerciseAngina  918 non-null    object 
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object 
 11  HeartDisease    918 non-null    int64  
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB
None
   Age Sex Chest

In [ ]:
#Q13 classification
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from google.colab import files
uploaded=files.upload()
import os
print(os.listdir())

# i. Read dataset
df = pd.read_csv("student_performance.csv")

# ii. Separate features and target
X = df.drop(["grade", "student_id"], axis=1) # Dropping 'student_id' as it's not a feature for prediction
y = df["grade"]

# Feature Scaling (important for KNN)
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Function to run KNN for different splits
def run_knn(test_size):
    print("\n==============================")
    print(f"Train-Test Split: {int((1-test_size)*100)}:{int(test_size*100)}")

    # iii. Split dataset
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=test_size, random_state=42)

    # iv. KNN model (K = 5)
    model = KNeighborsClassifier(n_neighbors=5)

    # v. Train model
    model.fit(X_train, y_train)

    # Prediction
    y_pred = model.predict(X_test)

    # vi. Evaluation
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Precision:", precision_score(y_test, y_pred, average='weighted'))
    print("Recall:", recall_score(y_test, y_pred, average='weighted'))
    print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

    return model

# Run for all splits
model_70 = run_knn(0.3)   # 70:30
model_60 = run_knn(0.4)   # 60:40
model_80 = run_knn(0.2)   # 80:20

# vii. Predict for new data
# Example input (replace with actual feature values)
new_data = [[75, 80, 70, 65]] # These should correspond to 'weekly_self_study_hours', 'attendance_percentage', 'class_participation', 'total_score'
new_data = scaler.transform(new_data)

prediction = model_80.predict(new_data)
print("\nPredicted Result for new data:", prediction)

Saving student_performance.csv to student_performance (5).csv
['.config', 'student_performance.csv', 'student_performance (2).csv', 'student_performance (1).csv', 'student_performance (5).csv', 'student_performance (3).csv', 'student_performance (4).csv', 'sample_data']

Train-Test Split: 70:30
Accuracy: 0.98387
Precision: 0.9838596372857051
Recall: 0.98387
F1 Score: 0.9838591258817382
Confusion Matrix:
 [[163571   1052      0      0      0]
 [  1133  75781    775      0      0]
 [     0    884  41308    246      0]
 [     0      0    515  12792     75]
 [     0      0      0    159   1709]]

Train-Test Split: 60:40
Accuracy: 0.9832225
Precision: 0.9832090355271497
Recall: 0.9832225
F1 Score: 0.9832100439314341
Confusion Matrix:
 [[217996   1437      0      0      0]
 [  1559 100858   1042      0      0]
 [     0   1243  55022    364      0]
 [     0      0    739  17158    109]
 [     0      0      0    218   2255]]

Train-Test Split: 80:20
Accuracy: 0.984425
Precision: 0.984415639560

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [ ]:
#Q14 classification

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
from google.colab import files
uploaded=files.upload()
import os
print(os.listdir())

# Load dataset
df = pd.read_csv("loan_data.csv")
print(df.columns)

# Separate features and target
X = df.drop("loan_status", axis=1)
y = df["loan_status"]
df = df.dropna()

# Encode categorical data
le = LabelEncoder()
for col in X.columns:
    if X[col].dtype == 'object':
        X[col] = le.fit_transform(X[col])

y = le.fit_transform(y)

# Scaling
scaler = StandardScaler()
X = scaler.fit_transform(X)

print("Unique target values:", np.unique(y))
print("Sample target values:", y[:10])

# Train-test split (70:30)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# KNN model
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)

# Prediction
y_pred = model.predict(X_test)

# Evaluation
print("\nLoan Dataset Results:")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred,average='weighted'))
print("Recall:", recall_score(y_test, y_pred,average='weighted'))
print("F1 Score:", f1_score(y_test, y_pred,average='weighted'))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# New prediction
new_sample = [X[0]]
print("Prediction:", model.predict([new_sample[0]]))

Saving loan_data (1).csv to loan_data (1).csv
['.config', 'heart.csv', 'loan_data (1).csv', 'heart (1).csv', 'loan_data.csv', 'heart (2).csv', 'heart (3).csv', 'sample_data']
Index(['person_age', 'person_gender', 'person_education', 'person_income',
       'person_emp_exp', 'person_home_ownership', 'loan_amnt', 'loan_intent',
       'loan_int_rate', 'loan_percent_income', 'cb_person_cred_hist_length',
       'credit_score', 'previous_loan_defaults_on_file', 'loan_status'],
      dtype='object')
Unique target values: [0 1]
Sample target values: [1 0 1 1 1 1 1 1 1 1]

Loan Dataset Results:
Accuracy: 0.8899259259259259
Precision: 0.8875221724567054
Recall: 0.8899259259259259
F1 Score: 0.8884071298076986
Confusion Matrix:
 [[9860  633]
 [ 853 2154]]
Prediction: [1]


In [ ]:
import os
print(os.listdir())


['.config', 'CVD_cleaned.csv (1).zip', 'CVD_cleaned.csv (2).zip', 'CVD_cleaned.csv.zip', 'sample_data']


In [ ]:
import zipfile

with zipfile.ZipFile("CVD_cleaned.csv.zip", 'r') as zip_ref:
    zip_ref.extractall()

In [ ]:
import os
print(os.listdir())

['.config', 'CVD_cleaned.csv', 'CVD_cleaned.csv (1).zip', 'CVD_cleaned.csv (2).zip', 'CVD_cleaned.csv.zip', 'sample_data']


In [ ]:
import os
print(os.listdir())

['.config', 'sample_data']
